version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-invoeaser
    environment:
      POSTGRES_DB: invoeaser_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoeaser-network

  redis:
    image: redis:latest
    container_name: redis-invoeaser
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - invoeaser-network
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-invoeaser
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - invoeaser-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  invoeaser-network:
    driver: bridge